### ISSUE TITLE
Fullresponse with MQX

### ISSUE THREAD

**Issue by elenafol** [pylhc/Beta-Beat.src#190]
fullresponse_pandas.py (version in lintrack) using madx as creator and including MQX to variables list is failing. The problem seems to be in generation of twiss for twiss.kqx.l5 (one of the circuits in MQX). 

Error message: 

Traceback (most recent call last):
  File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/generate_fullresponse_pandas.py", line 142, in <module>
    create_response()
  File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/utils/entrypoint.py", line 356, in wrapper
    return func(options, unknown_options)
  File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/generate_fullresponse_pandas.py", line 125, in create_response
    accel_inst, opt.variable_categories, delta_k=opt.delta_k
  File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/correction/fullresponse/response_madx.py", line 71, in generate_fullresponse
    return fullresponse
  File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/correction/fullresponse/response_madx.py", line 148, in _load_madx_results
    return var_to_twiss
  File "/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: [Errno 2] No such file or directory: u'/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2019-05-03/models/LHCB1/flattele60cm_21/twiss.kqx.l5'

Options used: --accel lhc --lhcmode lhc_runII_2018 --beam 1 --creator madx --variables MQ MQM MQY MQW MQT MQX

The script did not stop after crashing, it was just hanging forever.

**Comment by rogeliotomas** [comment]
Hi Elena,reducing the size of the dk should solve your problem for now. The code should detect a madx crash as in the previous version of the code.ciaoro
-------- Message d'origine --------De : elenafol <notifications@github.com> Date : 17.07.19  5:41 PM  (GMT+01:00) À : "pylhc/Beta-Beat.src" <Beta-Beat.src@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [pylhc/Beta-Beat.src] Fullresponse with MQX (#190) fullresponse_pandas.py (version in lintrack) using madx as creator and including MQX to variables list is failing. The problem seems to be in generation of twiss for twiss.kqx.l5 (one of the circuits in MQX).
Error message:
Traceback (most recent call last):
File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/generate_fullresponse_pandas.py", line 142, in 
create_response()
File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/utils/entrypoint.py", line 356, in wrapper
return func(options, unknown_options)
File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/generate_fullresponse_pandas.py", line 125, in create_response
accel_inst, opt.variable_categories, delta_k=opt.delta_k
File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/correction/fullresponse/response_madx.py", line 71, in generate_fullresponse
return fullresponse
File "/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/correction/fullresponse/response_madx.py", line 148, in _load_madx_results
return var_to_twiss
File "/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
return self.map_async(func, iterable, chunksize).get()
File "/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
raise self._value
IOError: [Errno 2] No such file or directory: u'/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2019-05-03/models/LHCB1/flattele60cm_21/twiss.kqx.l5'
Options used: --accel lhc --lhcmode lhc_runII_2018 --beam 1 --creator madx --variables MQ MQM MQY MQW MQT MQX
The script did not stop after crashing, it was just hanging forever.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pylhc/Beta-Beat.src/issues/190?email_source=notifications\u0026email_token=AAUNH6DUCMJ77ALOHH5F6WLP744RTA5CNFSM4IERZGMKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7Y376A",
"url": "https://github.com/pylhc/Beta-Beat.src/issues/190?email_source=notifications\u0026email_token=AAUNH6DUCMJ77ALOHH5F6WLP744RTA5CNFSM4IERZGMKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7Y376A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
