### ISSUE TITLE
DPP crashing in GetLLM when no DPP

### ISSUE THREAD

**Issue by fscarlier** [pylhc/Beta-Beat.src#77]
usage: GetLLM.py [-h] --accel {esrf,psbooster,CPS,lhc}
GetLLM.py: error: argument --accel: invalid choice: 'LHCB1' (choose from 'esrf', 'psbooster', 'CPS', 'lhc')
WARNING | Loading accelerator class failed. | GetLLM.GetLLM
WARNING | Suppose that the old command line arguments were used | GetLLM.GetLLM
WARNING | and guess what the right accelerator might be | GetLLM.GetLLM
   INFO | ['--accel=LHCB1', '--model=/home/fcarlier/fcarlie2/BB_MD/2017-05-30/models/LHCB1/BB_inj_rightTunes/twiss.dat'] | GetLLM.GetLLM
   INFO | Starting GetLLM V3.0.0 Dev | GetLLM.GetLLM
Traceback (most recent call last):
  File "/afs/cern.ch/work/f/fcarlier/public/Beta-Beat.src/GetLLM/GetLLM.py", line 1261, in <module>
    _start()
  File "/afs/cern.ch/work/f/fcarlier/public/Beta-Beat.src/GetLLM/GetLLM.py", line 1257, in _start
    union=options.union)
  File "/afs/cern.ch/work/f/fcarlier/public/Beta-Beat.src/GetLLM/GetLLM.py", line 356, in main
    twiss_d, files_dict = _analyse_src_files(getllm_d, twiss_d, files_to_analyse, nonlinear, files_dict, use_average, calibration_twiss, accelerator.get_model_tfs())
  File "/afs/cern.ch/work/f/fcarlier/public/Beta-Beat.src/GetLLM/GetLLM.py", line 597, in _analyse_src_files
    tfs_files_x = _arrange_dpp(tfs_files_x)
  File "/afs/cern.ch/work/f/fcarlier/public/Beta-Beat.src/GetLLM/GetLLM.py", line 739, in _arrange_dpp
    only_dpp = list_of_tfs[0].headers["DPP"]
KeyError: 'DPP'

**Comment by elenafol** [comment]
Solved in commit cf2ab81
